
nome = input("Digite seu nome: ")
idade = input("Digite sua idade: ")

print(f"seu nome é {nome}".format(nome))
print("seu nome invertido é {}".format(nome[::-1]))
print("seu nome contem ( ou nao ) espaços? {}".format(' ') in nome)
print("seu nome tem {n} letras".format(n = len(nome)))
print("a ultima letra do seu nome é {}".format(nome[-1]))
print("a primeira letra do seu nome é {}".format(nome[0]))

if 
    print("desculpe, voce deixou um campos vazios.")